language: node_js
node_js:
  - 7
  - 6
before_install:
  - npm config set depth 0
script:
  - npm run lint
  - npm run build
after_success:
  - rm -fr ./dist && npm run build && semantic-release pre && npm publish && semantic-release post
notifications:
  email: false
sudo: false
